[package]
name = "rtrec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rtrec"  # This should match the module name
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.0" # MessagePack support for Serde
serde_derive = "1.0" # Derive macros for Serde
rusoto_core = "0.46"
rusoto_s3 = "0.46"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"

[dependencies.pyo3]
version = "0.19"

[dev-dependencies]
# anyhow = "1.0"  # For error handling in tests

[features]
extension-module = ["pyo3/extension-module"]

[package.metadata.maturin]
bindings = "pyo3"
