[package]
name = "rtrec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rtrec"  # This should match the module name
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
# no dependencies

[dependencies.pyo3]
version = "0.19"

[features]
extension-module = ["pyo3/extension-module"]

[package.metadata.maturin]
bindings = "pyo3"
