[project]
name = "rtrec"
version = "0.1.0"
description = "An realtime recommendation system supporting online updates"
authors = [
    { name = "myui", email = "myui@apache.org" }
]
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
    "numpy>=2.1.2",
    "scikit-learn>=1.5.2",
    "pandas>=2.2.3",
    "fastapi>=0.115.4",
    "pydantic>=2.9.2",
    "uvicorn>=0.32.0",
    "httpx>=0.27.2",
    "boto3>=1.35.50",
    "tqdm>=4.67.0",
    "polars>=1.13.1",
    "pyarrow>=18.0.0",
]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust",
]

[project.urls]
homepage = "https://github.com/myui/rtrec"
repository = "https://github.com/myui/rtrec"

[build-system]
requires = ["maturin>=0.13,<2.0"]
build-backend = "maturin"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.3",
]

[tool.maturin]
python-source = "."
module-name = "rtrec._lowlevel"

# This ensures that Maturin uses the correct Cargo profile for releases
cargo-extra-args = ["--release"]

# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
addopts = "-s"
testpaths = [ "tests" ]
