[env]

LIBRARY_PATH = "/Users/myui/.rye/py/cpython@3.12.5/lib"
LD_LIBRARY_PATH = "/Users/myui/.rye/py/cpython@3.12.5/lib"
DYLD_LIBRARY_PATH = "/Users/myui/.rye/py/cpython@3.12.5/lib"

[build]
rustflags = ["-C", "target-cpu=native"]  # custom flags to pass to all compiler invocations
pipelining = true                        # rustc pipelining

# see https://deterministic.space/high-performance-rust.html
[profile.release]
opt-level = 2
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1
debug = true

# see https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels for haswell instructions
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=haswell"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=apple-m1"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-m1"]
